### ISSUE TITLE
Thoughts on refactoring pi3d_demos version

### ISSUE THREAD

**Issue by paddywwoof** [helgeerbe/picture_frame#2]
Hi @helgeerbe you've done some great stuff here. I've started to think about refactoring PictureFrame2020 (not just because of the bad 2020 karma) I had intended to break it into different functional classes very much along the lines you have but I'm not sure whether to just adopt your code as it is and add in the 'improvements' which have happened since you diverged. If I can keep it compatible with Home Assistant but still work without it - the main thing is that Wolfgang's setup will work (almost) unaltered; there's a lot of really good work in his picture frame blog and the less he has to re-write the better!

One thing has occurred to me (I've only just started to think about this so more will appear when I actually start to hack code):
 make the file_list (and associated date, GPS, exif etc data) into an sqlite database see https://github.com/pi3d/pi3d_demos/discussions/41#discussioncomment-268838

PS you might want to enable github discussions and transfer this as it's not really an issue.

**Comment by helgeerbe** [comment]
Moved to discussions https://github.com/helgeerbe/picture_frame/discussions/5 and closed.
